route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discordapp.com/api/webhooks/1164580324194406441/rLwzZDatrqRtZoqmmoMcRYzb_ovdFY4b-AccoCXhli844WnqS42Dm1PZkoJ8DFj4Ws5O
