kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      group_by: ['alertname', 'job']

      group_wait: 10s
      repeat_interval: 1m
      receiver: discord

    receivers: 
    - name: discord
      discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1172133872478195783/8nKpEWxMOJ3ym81GMkp5DFet29PD62cgNrzYHxQcjhpMqhJuZojKXEQrGs0FzJN9SMjq
